stages:
  - lint
  - test
  - build

lint:
  stage: lint
  image: golangci/golangci-lint:latest
  allow_failure: true
  script:
    - golangci-lint run

test:
  stage: test
  image: golang:1.24
  script:
    - go test -v ./...


build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t service_todo_app -f ./Dockerfile .




