image: golang:1.24

stages:
#  - lint
#  - test
  - deploy

#lint:
#  stage: lint
#  image: golangci/golangci-lint:latest
#  allow_failure: true
#  script:
#    - golangci-lint run
#
#test:
#  stage: test
#  image: golang:1.24
#  script:
#    - go test -v ./...

deploy:
  stage: deploy
  script:
    - docker-compose up -d --build

