run:
  exclude-dirs:
    - "vendor"
    - "mocks"
  timeout: 5m

linters-settings:
  gofmt:
    simplify: true

linters:
  enable:
    - govet         # Поиск ошибок в коде
    - errcheck      # Проверка на непроверенные ошибки
    - staticcheck   # Анализ кода на наличие багов
    - unused        # Поиск неиспользуемых переменных/функций
    - gosimple      # Упрощение кода
    - ineffassign   # Поиск неинициализированных переменных
    - goconst       # Проверка на повторяющиеся строковые/числовые значения
    - gofmt         # Автоформатирование
    - revive        # Расширенный стиль-контроль
    - goimports
